# * Try to find the SVT-AV1 encoder library Once done this will define
#
# SVTAV1_ROOT - A list of search hints
#
# SVTAV1_FOUND - system has SVT-AV1 encoder SVTAV1_INCLUDE_DIRS - the SVT-AV1
# include directory SVTAV1_LIBRARIES - SVT-AV1 encoder library

set(SVTAV1_MIN_VERSION "3.0")

if(UNIX AND NOT ANDROID)
  find_package(PkgConfig QUIET)
  pkg_check_modules(PC_SVTAV1 QUIET SvtAv1Enc)
endif(UNIX AND NOT ANDROID)

if(SVTAV1_INCLUDE_DIR AND SVTAV1_LIBRARY)
  set(SVTAV1_FIND_QUIETLY TRUE)
endif(SVTAV1_INCLUDE_DIR AND SVTAV1_LIBRARY)

find_path(SVTAV1_INCLUDE_DIR NAMES EbSvtAv1Enc.h PATH_SUFFIXES include include/svt-av1 HINTS ${SVTAV1_ROOT}
                                                                                             ${PC_SVTAV1_INCLUDE_DIRS}
)
find_library(SVTAV1_LIBRARY NAMES SvtAv1Enc PATH_SUFFIXES lib HINTS ${SVTAV1_ROOT} ${PC_SVTAV1_LIBRARY_DIRS})

set(SVTAV1_VERSION ${PC_SVTAV1_VERSION})
if(SVTAV1_INCLUDE_DIR AND NOT SVTAV1_VERSION)
  set(SVTAV1_VERSION_FILE "${SVTAV1_INCLUDE_DIR}/EbSvtAv1.h")
  if(EXISTS "${SVTAV1_VERSION_FILE}")
    file(STRINGS "${SVTAV1_VERSION_FILE}" SVTAV1_VERSION_MAJOR REGEX "^#define[\t ]+SVT_AV1_VERSION_MAJOR[\t ]+[0-9]+")
    file(STRINGS "${SVTAV1_VERSION_FILE}" SVTAV1_VERSION_MINOR REGEX "^#define[\t ]+SVT_AV1_VERSION_MINOR[\t ]+[0-9]+")
    file(STRINGS "${SVTAV1_VERSION_FILE}" SVTAV1_VERSION_PATCHLEVEL
         REGEX "^#define[\t ]+SVT_AV1_VERSION_PATCHLEVEL[\t ]+[0-9]+"
    )

    if(SVTAV1_VERSION_MAJOR AND SVTAV1_VERSION_MINOR AND SVTAV1_VERSION_PATCHLEVEL)
      string(REGEX REPLACE ".*[\t ]([0-9]+)$" "\\1" SVTAV1_VERSION_MAJOR "${SVTAV1_VERSION_MAJOR}")
      string(REGEX REPLACE ".*[\t ]([0-9]+)$" "\\1" SVTAV1_VERSION_MINOR "${SVTAV1_VERSION_MINOR}")
      string(REGEX REPLACE ".*[\t ]([0-9]+)$" "\\1" SVTAV1_VERSION_PATCHLEVEL "${SVTAV1_VERSION_PATCHLEVEL}")
      set(SVTAV1_VERSION "${SVTAV1_VERSION_MAJOR}.${SVTAV1_VERSION_MINOR}.${SVTAV1_VERSION_PATCHLEVEL}")
    endif()
  endif()
endif()

set(SVTAV1_VERSION_OK FALSE)
if(SVTAV1_VERSION AND NOT SVTAV1_VERSION VERSION_LESS SVTAV1_MIN_VERSION)
  set(SVTAV1_VERSION_OK TRUE)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  SVTAV1 REQUIRED_VARS SVTAV1_LIBRARY SVTAV1_INCLUDE_DIR SVTAV1_VERSION_OK
  VERSION_VAR SVTAV1_VERSION REASON_FAILURE_MESSAGE
                             "SVT-AV1 encoder version ${SVTAV1_MIN_VERSION} or newer is required"
)

if(SVTAV1_FOUND)
  set(SVTAV1_FOUND ON CACHE BOOL "SVTAV1")
  set(SVTAV1_LIBRARIES ${SVTAV1_LIBRARY} CACHE STRING "SVTAV1")
  set(SVTAV1_INCLUDE_DIRS ${SVTAV1_INCLUDE_DIR} CACHE STRING "SVTAV1")
  set(SVTAV1_VERSION ${SVTAV1_VERSION} CACHE STRING "SVTAV1")
endif(SVTAV1_FOUND)

if(SVTAV1_FOUND)
  if(NOT SVTAV1_FIND_QUIETLY)
    message(STATUS "Found SVTAV1: ${SVTAV1_LIBRARIES} (${SVTAV1_VERSION})")
  endif(NOT SVTAV1_FIND_QUIETLY)
else(SVTAV1_FOUND)
  if(SVTAV1_FIND_REQUIRED)
    message(FATAL_ERROR "SVTAV1 was not found")
  endif(SVTAV1_FIND_REQUIRED)
endif(SVTAV1_FOUND)

mark_as_advanced(SVTAV1_INCLUDE_DIRS SVTAV1_LIBRARIES SVTAV1_FOUND SVTAV1_VERSION)
