# * Try to find the dav1d AV1 decoder library Once done this will define
#
# DAV1D_ROOT - A list of search hints
#
# DAV1D_FOUND - system has dav1d dav1d_FOUND - system has dav1d
# DAV1D_INCLUDE_DIRS - the dav1d include directory DAV1D_LIBRARIES - dav1d
# library

set(DAV1D_MIN_VERSION "1.0")

if(UNIX AND NOT ANDROID)
  find_package(PkgConfig QUIET)
  pkg_check_modules(PC_DAV1D QUIET dav1d)
endif(UNIX AND NOT ANDROID)

if(DAV1D_INCLUDE_DIR AND DAV1D_LIBRARY)
  set(DAV1D_FIND_QUIETLY TRUE)
endif(DAV1D_INCLUDE_DIR AND DAV1D_LIBRARY)

find_path(DAV1D_INCLUDE_DIR NAMES dav1d/dav1d.h PATH_SUFFIXES include HINTS ${DAV1D_ROOT} ${PC_DAV1D_INCLUDE_DIRS})
find_library(DAV1D_LIBRARY NAMES dav1d PATH_SUFFIXES lib HINTS ${DAV1D_ROOT} ${PC_DAV1D_LIBRARY_DIRS})

set(DAV1D_VERSION ${PC_DAV1D_VERSION})
set(DAV1D_VERSION_OK FALSE)
if(DAV1D_VERSION AND NOT DAV1D_VERSION VERSION_LESS DAV1D_MIN_VERSION)
  set(DAV1D_VERSION_OK TRUE)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  dav1d REQUIRED_VARS DAV1D_LIBRARY DAV1D_INCLUDE_DIR DAV1D_VERSION_OK
  VERSION_VAR DAV1D_VERSION REASON_FAILURE_MESSAGE "dav1d decoder version ${DAV1D_MIN_VERSION} or newer is required"
)

if(dav1d_FOUND)
  set(DAV1D_FOUND ON CACHE BOOL "DAV1D" FORCE)
  set(dav1d_FOUND ON CACHE BOOL "dav1d" FORCE)
  set(DAV1D_LIBRARIES ${DAV1D_LIBRARY} CACHE STRING "DAV1D" FORCE)
  set(DAV1D_INCLUDE_DIRS ${DAV1D_INCLUDE_DIR} CACHE STRING "DAV1D" FORCE)
  set(DAV1D_VERSION ${DAV1D_VERSION} CACHE STRING "DAV1D" FORCE)
else()
  set(DAV1D_FOUND OFF CACHE BOOL "DAV1D" FORCE)
  set(dav1d_FOUND OFF CACHE BOOL "dav1d" FORCE)
endif(dav1d_FOUND)

if(DAV1D_FOUND)
  if(NOT DAV1D_FIND_QUIETLY)
    message(STATUS "Found dav1d: ${DAV1D_LIBRARIES} (${DAV1D_VERSION})")
  endif(NOT DAV1D_FIND_QUIETLY)
else(DAV1D_FOUND)
  if(dav1d_FIND_REQUIRED)
    message(FATAL_ERROR "dav1d was not found")
  endif(dav1d_FIND_REQUIRED)
endif(DAV1D_FOUND)

mark_as_advanced(DAV1D_INCLUDE_DIRS DAV1D_LIBRARIES DAV1D_FOUND dav1d_FOUND DAV1D_VERSION)
